In [13]:
from keras.datasets import mnist
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

Using TensorFlow backend.
/home/adam/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/adam/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/adam/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/adam/.local/lib/python3.6/site-packages/tensorflow/python/framewo

In [14]:
from keras import models
from keras import layers
network = models.Sequential()
network.add(layers.Dense(512, activation='relu', input_shape=(28 * 28,)))
network.add(layers.Dense(10, activation='softmax'))

Instructions for updating:
Colocations handled automatically by placer.


In [15]:
network.compile(optimizer='rmsprop',
loss='categorical_crossentropy',
metrics=['accuracy'])

In [16]:
network.compile(optimizer='rmsprop',
loss='categorical_crossentropy',
metrics=['accuracy'])

In [17]:
train_images = train_images.reshape((60000, 28 * 28))
train_images = train_images.astype('float32') / 255
test_images = test_images.reshape((10000, 28 * 28))
test_images = test_images.astype('float32') / 255

In [18]:
from keras.utils import to_categorical
train_labels = to_categorical(train_labels)
test_labels = to_categorical(test_labels)

In [19]:
network.fit(train_images, train_labels, epochs=5, batch_size=128)

Instructions for updating:
Use tf.cast instead.
Epoch 1/5
60000/60000 [==============================] - 4s 62us/step - loss: 0.2578 - accuracy: 0.9249
Epoch 2/5
60000/60000 [==============================] - 4s 59us/step - loss: 0.1026 - accuracy: 0.9693
Epoch 3/5
60000/60000 [==============================] - 3s 58us/step - loss: 0.0678 - accuracy: 0.9799
Epoch 4/5
60000/60000 [==============================] - 3s 58us/step - loss: 0.0483 - accuracy: 0.9856
Epoch 5/5
60000/60000 [==============================] - 4s 60us/step - loss: 0.0360 - accuracy: 0.9893


In [20]:
 test_loss, test_acc = network.evaluate(test_images, test_labels)

10000/10000 [==============================] - 0s 43us/step


In [21]:
print('test_acc:', test_acc)

test_acc: 0.9818000197410583


In [22]:
import numpy as np 
x = np.array(12)
x

array(12)

In [23]:
x.ndim

0

In [24]:
x = np.array([12,3,6,14])
x

array([12,  3,  6, 14])

In [25]:
x.ndim

1

In [26]:
x = np.array([[1,2,3,4,5],
             [6,7,8,9,10],
             [11,12,13,14,15]])
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [27]:
x.ndim

2

In [28]:
x = np.array([[[5, 78, 2, 34, 0],
[6, 79, 3, 35, 1],
[7, 80, 4, 36, 2]],
[[5, 78, 2, 34, 0],
[6, 79, 3, 35, 1],
[7, 80, 4, 36, 2]],
[[5, 78, 2, 34, 0],
[6, 79, 3, 35, 1],
[7, 80, 4, 36, 2]]])

x.ndim

3

In [29]:
from keras.datasets import mnist
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()
print(train_images.ndim)

3


In [30]:
print(train_images.shape)

(60000, 28, 28)


In [31]:
print(train_images.dtype)

uint8


In [32]:
digit = train_images[4]
import matplotlib.pyplot as plt
plt.imshow(digit, cmap=plt.cm.binary)
plt.show()

<Figure size 640x480 with 1 Axes>

In [33]:
my_slice = train_images[10:100]
print(my_slice.shape)

(90, 28, 28)


In [34]:
my_slice = train_images[10:100, :, :]
my_slice.shape

(90, 28, 28)

In [35]:
my_slice = train_images[10:100, 0:28, 0:28]
my_slice.shape


(90, 28, 28)

In [36]:
my_slice = train_images[:, 14:, 14:]
my_slice = train_images[:, 7:-7, 7:-7]
batch = train_images[:128]
batch = train_images[128:256]
batch = train_images[128 * 2:128 * (2 + 1)]


In [37]:
def naive_relu(x):
    assert len(x.shape) == 2
    x = x.copy()
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i, j] = max(x[i, j], 0)
    return x

In [38]:
def naive_add(x, y):
    assert len(x.shape) == 2
    assert x.shape == y.shape
    x = x.copy()
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i, j] += y[i, j]
    return x

In [39]:
import numpy as np 
x = 5
y = 7
z = x+y
z = np.maximum(z,0.)
print (z)


12.0


In [40]:
def naive_add_matrix_and_vector(x,y):
    assert lne(x.shape) == 2
    assert len(y.shape) == 1
    assert x.shape[1] == y.shape[0]
    
    x = x.copy()
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i,j] += y[j]
    return x








In [41]:
import numpy as np

def naive_vector_dot(x,y):
    assert len(x.shape) == 1
    assert len(y.shape) == 1
    assert x.shape[0] == y.shape[0]
    z = 0
    for i in range(x.shape[0]):
        z += x[i] * y[i]
    return z
def naive_matrix_vector_dot(x,y):
    assert len(x.shape) == 2
    assert len(y.shape) == 1
    assert x.shape[1] == y.shape[0]
    
    z = np.zeros(x.shape[0])
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            z[i] += x[i,j] * y[j]
    return z
def naive_matrix_vector_dot(x,y):
    z = np.zeros(x.shape[0])
    for i in range(x.shape[0]):
        z[i] = naive_vector_dot(x[i, :], y)
    return z

def naive_matrix_dot(x,y):
    assert len(x.shape) == 2
    assert len(y.shape) == 2
    assert x.shape[1] == y.shape[0]
    
    z = np.zeros((x.shape[0], y.shape[1]))
    for i in range(x.shape[0]):
        for j in range(y.shape[1]):
            row_x = x[i, :]
            column_y = y[:, j]
            z[i,j] = naive_vector_dot(row_x,column_y)
    return z



    

In [42]:
train_images = train_images.reshape((60000,28*28))

In [43]:
x = np.array([[0.,1.],
             [2.,3.],
             [4., 5.]])
print(x.shape)

(3, 2)


In [44]:
x = x.reshape((6,1))
x

array([[0.],
       [1.],
       [2.],
       [3.],
       [4.],
       [5.]])

In [48]:

x = np.zeros((300,20))
x = np.transpose(x)
print(x.shape)

(20, 300)


In [49]:
past_velocity = 0
momentum = 0.1
'''while loss > 0.01:
    w,loss,gradient = get_current_parameters()
    velocity = past_velocity*momentum + learning_rate*gradient
    w = w+momentum*velocity - learning_rate * gradient
    past_velocity = velocity 
    update_parameter(w)'''
    

NameError: name 'loss' is not defined

In [67]:
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()
train_images = train_images.reshape((60000, 28 * 28))
train_images = train_images.astype('float32') / 255
test_images = test_images.reshape((10000, 28 * 28))
test_images = test_images.astype('float32') / 255



network = models.Sequential()
network.add(layers.Dense(512, activation='relu', input_shape=(28 * 28,)))
network.add(layers.Dense(10, activation='softmax'))

network.compile(optimizer='rmsprop',
loss='sparse_categorical_crossentropy',
metrics=['accuracy'])

network.fit(train_images, train_labels, epochs=5, batch_size=128)


Epoch 1/5
60000/60000 [==============================] - 4s 61us/step - loss: 0.2561 - accuracy: 0.9255
Epoch 2/5
60000/60000 [==============================] - 4s 62us/step - loss: 0.1025 - accuracy: 0.9691
Epoch 3/5
60000/60000 [==============================] - 4s 63us/step - loss: 0.0682 - accuracy: 0.9790
Epoch 4/5
60000/60000 [==============================] - 4s 60us/step - loss: 0.0491 - accuracy: 0.9852
Epoch 5/5
60000/60000 [==============================] - 4s 61us/step - loss: 0.0368 - accuracy: 0.9892
